# Generated by Django 4.1.3 on 2022-11-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WildfireReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=255)),
                ('reported_by', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
